version: '{build}'
image: Ubuntu1804

environment:
  matrix:
    - nodejs_version: '22'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g yarn
  - yarn install

build_script:
  - yarn run build

test_script:
  - yarn run lint
  - yarn run test
